name: command_cli
description: Library for creating cli tools that parses commands from arguments
version: 1.0.0
homepage: https://github.com/kemitix/command_dart

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  recase: ^4.0.0
  ansicolor: ^2.0.1

dev_dependencies:
  lints: ^1.0.1
